// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'AiHugDS_DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyD-5ByzRZEbt5uazVvS5i1EZa_U1CDn8Yk",
    appId: "1:450087150637:android:c210c7884fb1cabb58c4a4",
    messagingSenderId: "450087150637",
    projectId: "ai-logo-generatorlogo-creator",
    storageBucket: 'ai-logo-generatorlogo-creator.firebasestorage.app',
    iosBundleId: 'com.ailogo.logomaker',
  );


  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyD-5ByzRZEbt5uazVvS5i1EZa_U1CDn8Yk",
    appId: "1:450087150637:android:c210c7884fb1cabb58c4a4",
    messagingSenderId: "450087150637",
    projectId: "ai-logo-generatorlogo-creator",
    storageBucket: 'ai-logo-generatorlogo-creator.firebasestorage.app',
  );


}
